language: node_js
node_js:
- 8.12.0
sudo: required
services:
- docker
env:
  global:
  - CXX=g++-4.8
  matrix:
  - USE_SENTRY=1
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
- docker pull getsentry/sentry-cli
script:
- npm install
- npm run build:dll
- npm run build
before_deploy:
- bash deploy/sentry_release.sh
- find dist/ -type f -name "*.map" -delete
- zip -r dist.zip dist
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
  - secure: cjEyM6gdlAIpuax8HVfhisocCCbK8isLiII6Zl087fygU4JUikPQSOpt+HAw9oIFF8CK+WW+WGMPeisJrYnkrWPXfcA4PlSIsfmNNkzrE6rxVsFsmBGIR/dguX25k7n24Ht3N+xXNovMTYKBiTx47DZ/2Zvlzj4pyIyFy/pU92H5j/1eeH+wGg/tHNYAnoaSH/pGh23cXLpR4riM5JGMWlZ6NHiyTm3mpVT8BSpx6//5BCBWhXht3szlVNE2Ln9ukHeWqc+5TDIDkPpmkMsfLpwPPwFMmUdAMzO1Q9xbJj+O8TVYcT3ZGF/hfnSDqH0vzBaZ3fWijMD8uwKdLBPZpE5D0Dz+ec4dPwGn/7CGfgPc2tN9r6G89G/3qHEuUBZSurnAFJeJtvieOgBCByTeu8FWShiaLE1lUTEI/K1D2NXBBJYjYjeZnGC+T8QDzzWalkBhMfI/Gc4yj5/RfYKRrRV4Z+O+ngq33cVb6uaqZdnm645TkkaWOgpgx1Hh1/nXOeiYhKyC8TSk648bCJWYEmHnzoCClxrTEp/xNO6CA6yA2rdqPjuQNHRZJXnHtrUaZB2gpeFnO6UwLjpPc2TclvDIFOKKywN+zVoWstlNiNnd3xu4EiiS4ivhXcUfvyxjUEeM7GTlMekWxAzEGtd8tAb7vsrkAa+kRg50h+DFPsQ=
  file: dist.zip
  on:
    all_branches: true
    tags: true
