language: node_js
node_js:
- 8.12.0
sudo: required
services:
- docker
env:
  global:
  - CXX=g++-4.8
  matrix:
  - USE_SENTRY=1
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
- docker pull getsentry/sentry-cli
script:
- npm install
- npm run build:dll
- npm run build
before_deploy:
- bash deploy/sentry_release.sh
- find dist/ -type f -name "*.map" -delete
- zip -r dist.zip dist
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
  - secure: keBCxbyUz7G9v2GXOQw2tvo+Et5DP8Sl7Ol00D8lxfOfasM+U95jDuoR2KvnBOVf6EOAI2G2ofr9EygaktUqLAwh16Gi8zihoWBHrmqGbS6jkYyj763DKHE2GWVmhDUG8qMXY4GW1yKAfksnGHq/4Ivgcq7qlac4R35WQoO0tTx0V9YhDXt3UHBCt/MnraGCrvzS5dx7onVI/h+nx4cb8MuK0ke9DPIx6E9eC1yt/UTC3OD7aAdELx4bTgDvaNswn6kxk+O0lQA7fk4KR+9WGKOX7jiSL3zFdfCCcvfSnqbShGsCOjsJIrNjIwVgjSr9PLN0EIvfBKP+UE82YjwCM2dwR0y/x66ojRml8yq3WgeJF/OGvh8iuaDkPoqzeu3+8RRu+IVbYpoWq/111D2QKPSQvOmFi6qc4Mx6lBBHkX9L79gu6mY26b/aOXRG/bj5CE5w11YP7KVCyqGdlImsZxv6WimT363V2tFfN7lfbMhNtV/mavHMPCUI4G9pvzo3n3sLeVX209SGECKFt+WSiBcmXBshUFhmAduFfngN7FUMaIiDUivZvJaqjFqJGXr3b6hxOWTjesiiSgPcL9eeXelNyPMknlcGVwmZ2jaaUyYyE6FFDBlZFo7nTZ7gZuE93p2NNFzyFHFWlXdhfz30bFi3nnPz4kpdnbgeTBR6SRk=
  file: dist.zip
  on:
    all_branches: true
    tags: true
